//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProtoTypeTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIProtoTypeTest.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM 
        ///				[dbo].[tmp2] 
        ///WHERE
        ///				[sourcesystemid]	=  [[sourcesystemid]]
        ///			AND [targetproductid]	=  [[targetproductid]].
        /// </summary>
        internal static string ProductDeleteQuery {
            get {
                return ResourceManager.GetString("ProductDeleteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[tmp2]
        ///           (
        ///				[sourcesystemid]
        ///			   ,[targetproductid]
        ///			   ,[productid]
        ///			   ,[productname]
        ///			   ,[productdescription]
        ///			   ,[productimageurl]
        ///			   ,[rank]
        ///           )
        ///VALUES
        ///           (
        ///				[[sourcesystemid]]
        ///			   ,[[targetproductid]]
        ///			   ,[[productid]]
        ///			   ,[[productname]]
        ///			   ,[[productdescription]]
        ///			   ,[[productimageurl]]
        ///			   ,[[rank]]
        ///           ).
        /// </summary>
        internal static string ProductInsertQuery {
            get {
                return ResourceManager.GetString("ProductInsertQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM 
        ///				[dbo].[tmp3] 
        ///WHERE
        ///				[sourcesystemid]	=  [[sourcesystemid]]
        ///			AND [userid]	=  [[userid]].
        /// </summary>
        internal static string UserDeleteQuery {
            get {
                return ResourceManager.GetString("UserDeleteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[tmp3]
        ///           (
        ///				[sourcesystemid]
        ///			   ,[userid]
        ///			   ,[productid]
        ///			   ,[productname]
        ///			   ,[productdescription]
        ///			   ,[rank]
        ///			   ,[productimageurl]
        ///           )
        ///VALUES
        ///           (
        ///				[[sourcesystemid]]
        ///			   ,[[userid]]
        ///			   ,[[productid]]
        ///			   ,[[productname]]
        ///			   ,[[productdescription]]
        ///			   ,[[rank]]
        ///			   ,[[productimageurl]]
        ///           ).
        /// </summary>
        internal static string UserInsertQuery {
            get {
                return ResourceManager.GetString("UserInsertQuery", resourceCulture);
            }
        }
    }
}
